### ISSUE TITLE
What is pixelspermeter？

### ISSUE THREAD

**Issue by wdj577** [IAmS4n/TensorBoard_Plugin_WSI#1]
excuse me, How to calculate pixelspermeter value?

**Comment by IAmS4n** [comment]
For a standard WSI file, Openslide lib return two property of `PROPERTY_NAME_MPP_X` and `PROPERTY_NAME_MPP_Y`, which are the number of microns per pixel, so 10**6/MPP is the number of pixel per meter, which is `pixelspermeter`.

The same procedure in my code:
https://github.com/IAmS4n/TensorBoard_Plugin_WSI/blob/a927f616724bf80aa5c977d82658e30cb0d11df4/tensorboard_plugin_wsi/plugin.py#L123
https://github.com/IAmS4n/TensorBoard_Plugin_WSI/blob/a927f616724bf80aa5c977d82658e30cb0d11df4/tensorboard_plugin_wsi/static/slide.js#L36

If your file does not have these properties, you can estimate them and add them manually.
